In [6]:
# ============================================================
# Actividad 4: Manejo de Datos con Pandas
# ============================================================

import pandas as pd
import numpy as np

# ============================================================
# Dataset base
# ============================================================

datos = {
    'nombre':   ['Ana', 'Bob', 'Clara', 'Diego', 'Eva'],
    'edad':     [25, 30, 22, None, 28],
    'ciudad':   ['Madrid', 'Lima', 'Bogotá', 'Medellín', None],
    'producto': ['Laptop', 'Teléfono', 'Tablet', 'Laptop', 'Tablet'],
    'precio':   [1200, 800, 300, 1150, None],
    'stock':    [10, 15, 5, 8, 0]
}

df = pd.DataFrame(datos, index=['a', 'b', 'c', 'd', 'e'])
df.to_csv('actividad_semana4.csv', index=True)
print("=== DataFrame Base ===")
display(df)

# ============================================================
# 1) SERIES — crear y operar
# ============================================================

serie_lista = pd.Series([10, 20, 30, 40], index=['x', 'y', 'z', 'w'])
print("\n=== Serie desde lista ===")
display(serie_lista)

serie_dic = pd.Series({'manzana': 5, 'banana': 8, 'naranja': 3})
print("\n=== Serie desde diccionario ===")
display(serie_dic)

print("\nValor de 'banana':", serie_dic['banana'])
serie_dic['manzana'] = 10
print("Serie modificada ('manzana' = 10):")
display(serie_dic)

print("Serie multiplicada por 2:")
display(serie_dic * 2)

# ============================================================
# 2) DATAFRAME — crear y explorar
# ============================================================

datos_df = {
    'nombre': ['Luis', 'María', 'José'],
    'edad': [21, 35, 27],
    'ciudad': ['Quito', 'Caracas', 'Bogotá']
}
df2 = pd.DataFrame(datos_df, index=['x', 'y', 'z'])
print("\n=== DataFrame creado manualmente ===")
display(df2)

print("\nColumna 'nombre':")
display(df2['nombre'])

print("\nFila con loc['x']:")
display(df2.loc['x'])

print("\nFila con iloc[0]:")
display(df2.iloc[0])

# ============================================================
# 3) OPERACIONES BÁSICAS
# ============================================================

df['precio_descuento'] = df['precio'] * 0.9
df['stock'] = df['stock'] + 5
print("\n=== DataFrame con columna derivada y stock actualizado ===")
display(df)

# ============================================================
# 4) MANEJO DE DATOS FALTANTES
# ============================================================

print("\n=== Detección de nulos ===")
display(df.isna())

print("\n=== Conteo de faltantes por columna ===")
display(df.isna().sum())

df['edad'] = df['edad'].fillna(0)
df['ciudad'] = df['ciudad'].fillna('Desconocido')
df['precio'] = df['precio'].fillna(0)
print("\n=== DataFrame sin valores nulos ===")
display(df)

# ============================================================
# 5) SELECCIÓN Y FILTRADO
# ============================================================

print("\n=== Filas con precio > 500 ===")
display(df[df['precio'] > 500])

print("\n=== Productos 'Laptop' con stock > 5 ===")
display(df[(df['producto'] == 'Laptop') & (df['stock'] > 5)])

# ============================================================
# 6) ORDENAR DATOS
# ============================================================

print("\n=== Ordenado por edad (ascendente) ===")
display(df.sort_values('edad'))

print("\n=== Ordenado por precio (descendente, llenando nulos con 0) ===")
display(df.sort_values('precio', ascending=False))

# ============================================================
# 7) ESTADÍSTICAS BÁSICAS
# ============================================================

print("\n=== Estadísticas de columnas numéricas ===")
display(df.describe())

print("\n=== Conteo de valores en 'producto' ===")
display(df['producto'].value_counts())

# ============================================================
# 8) LEER Y GUARDAR DATOS
# ============================================================

df_leido = pd.read_csv('actividad_semana4.csv')
print("\n=== CSV leído desde archivo ===")
display(df_leido.head())

df[['nombre', 'producto', 'precio_descuento']].to_csv('datos_filtrados.csv', index=False)
print("\nArchivo 'datos_filtrados.csv' guardado correctamente.")

# ============================================================
# 9) EJERCICIO INTEGRADO
# ============================================================

df['precio_descuento'] = df['precio'] * 0.9
df_filtrado = df[df['stock'] > 5]
df_ordenado = df_filtrado.sort_values('precio_descuento')
df_ordenado.to_csv('inventario_procesado.csv', index=False)

print("\n=== DataFrame final procesado ===")
display(df_ordenado)
print("\nArchivo 'inventario_procesado.csv' generado exitosamente.")

=== DataFrame Base ===

  nombre  edad    ciudad  producto  precio  stock
a    Ana  25.0    Madrid    Laptop  1200.0     10
b    Bob  30.0      Lima  Teléfono   800.0     15
c  Clara  22.0    Bogotá    Tablet   300.0      5
d  Diego   NaN  Medellín    Laptop  1150.0      8
e    Eva  28.0      None    Tablet     NaN      0

=== Serie desde lista ===

x    10
y    20
z    30
w    40
dtype: int64

=== Serie desde diccionario ===

manzana    5
banana     8
naranja    3
dtype: int64

Valor de 'banana': 8
Serie modificada ('manzana' = 10):

manzana    10
banana      8
naranja     3
dtype: int64

Serie multiplicada por 2:

manzana    20
banana     16
naranja     6
dtype: int64

=== DataFrame creado manualmente ===

  nombre  edad   ciudad
x   Luis    21    Quito
y  María    35  Caracas
z   José    27   Bogotá

Columna 'nombre':

x     Luis
y    María
z     José
Name: nombre, dtype: object

Fila con loc['x']:

nombre     Luis
edad         21
ciudad    Quito
Name: x, dtype: object

Fila con iloc[0]:

nombre     Luis
edad         21
ciudad    Quito
Name: x, dtype: object

=== DataFrame con columna derivada y stock actualizado ===

  nombre  edad    ciudad  producto  precio  stock  precio_descuento
a    Ana  25.0    Madrid    Laptop  1200.0     15            1080.0
b    Bob  30.0      Lima  Teléfono   800.0     20             720.0
c  Clara  22.0    Bogotá    Tablet   300.0     10             270.0
d  Diego   NaN  Medellín    Laptop  1150.0     13            1035.0
e    Eva  28.0      None    Tablet     NaN      5               NaN

=== Detección de nulos ===

   nombre   edad  ciudad  producto  precio  stock  precio_descuento
a   False  False   False     False   False  False             False
b   False  False   False     False   False  False             False
c   False  False   False     False   False  False             False
d   False   True   False     False   False  False             False
e   False  False    True     False    True  False              True

=== Conteo de faltantes por columna ===

nombre              0
edad                1
ciudad              1
producto            0
precio              1
stock               0
precio_descuento    1
dtype: int64

=== DataFrame sin valores nulos ===

  nombre  edad       ciudad  producto  precio  stock  precio_descuento
a    Ana  25.0       Madrid    Laptop  1200.0     15            1080.0
b    Bob  30.0         Lima  Teléfono   800.0     20             720.0
c  Clara  22.0       Bogotá    Tablet   300.0     10             270.0
d  Diego   0.0     Medellín    Laptop  1150.0     13            1035.0
e    Eva  28.0  Desconocido    Tablet     0.0      5               NaN

=== Filas con precio > 500 ===

  nombre  edad    ciudad  producto  precio  stock  precio_descuento
a    Ana  25.0    Madrid    Laptop  1200.0     15            1080.0
b    Bob  30.0      Lima  Teléfono   800.0     20             720.0
d  Diego   0.0  Medellín    Laptop  1150.0     13            1035.0

=== Productos 'Laptop' con stock > 5 ===

  nombre  edad    ciudad producto  precio  stock  precio_descuento
a    Ana  25.0    Madrid   Laptop  1200.0     15            1080.0
d  Diego   0.0  Medellín   Laptop  1150.0     13            1035.0

=== Ordenado por edad (ascendente) ===

  nombre  edad       ciudad  producto  precio  stock  precio_descuento
d  Diego   0.0     Medellín    Laptop  1150.0     13            1035.0
c  Clara  22.0       Bogotá    Tablet   300.0     10             270.0
a    Ana  25.0       Madrid    Laptop  1200.0     15            1080.0
e    Eva  28.0  Desconocido    Tablet     0.0      5               NaN
b    Bob  30.0         Lima  Teléfono   800.0     20             720.0

=== Ordenado por precio (descendente, llenando nulos con 0) ===

  nombre  edad       ciudad  producto  precio  stock  precio_descuento
a    Ana  25.0       Madrid    Laptop  1200.0     15            1080.0
d  Diego   0.0     Medellín    Laptop  1150.0     13            1035.0
b    Bob  30.0         Lima  Teléfono   800.0     20             720.0
c  Clara  22.0       Bogotá    Tablet   300.0     10             270.0
e    Eva  28.0  Desconocido    Tablet     0.0      5               NaN

=== Estadísticas de columnas numéricas ===

            edad       precio     stock  precio_descuento
count   5.000000     5.000000   5.00000          4.000000
mean   21.000000   690.000000  12.60000        776.250000
std    12.124356   527.257053   5.59464        373.572282
min     0.000000     0.000000   5.00000        270.000000
25%    22.000000   300.000000  10.00000        607.500000
50%    25.000000   800.000000  13.00000        877.500000
75%    28.000000  1150.000000  15.00000       1046.250000
max    30.000000  1200.000000  20.00000       1080.000000

=== Conteo de valores en 'producto' ===

producto
Laptop      2
Tablet      2
Teléfono    1
Name: count, dtype: int64

=== CSV leído desde archivo ===

  Unnamed: 0 nombre  edad    ciudad  producto  precio  stock
0          a    Ana  25.0    Madrid    Laptop  1200.0     10
1          b    Bob  30.0      Lima  Teléfono   800.0     15
2          c  Clara  22.0    Bogotá    Tablet   300.0      5
3          d  Diego   NaN  Medellín    Laptop  1150.0      8
4          e    Eva  28.0       NaN    Tablet     NaN      0

Archivo 'datos_filtrados.csv' guardado correctamente.

=== DataFrame final procesado ===

  nombre  edad    ciudad  producto  precio  stock  precio_descuento
c  Clara  22.0    Bogotá    Tablet   300.0     10             270.0
b    Bob  30.0      Lima  Teléfono   800.0     20             720.0
d  Diego   0.0  Medellín    Laptop  1150.0     13            1035.0
a    Ana  25.0    Madrid    Laptop  1200.0     15            1080.0

Archivo 'inventario_procesado.csv' generado exitosamente.